# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-07 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_auto_20181204_1056'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.Menu')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_menu',
            field=models.ManyToManyField(through='client.OrderMenu', to='partner.Menu'),
        ),
        migrations.AddField(
            model_name='ordermenu',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Order'),
        ),
    ]
